image: python3.14

stages:
  - build_bindings
  - build_project

before_script:
  - pip install scons

variables:
  GODOT_CPP_PATH: godot-cpp
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key:
    files:
      - .gitmodules
      - $GODOT_CPP_PATH/.git/HEAD
  paths:
    - $GODOT_CPP_PATH/bin/

build_bindings:
  stage: build_bindings
  script:
    - cd $GODOT_CPP_PATH
    - scons platform=linux -j$(nproc)
  artifacts:
    paths:
      - $GODOT_CPP_PATH/bin/

build_project:
  stage: build
  needs: ["build_bindings"]
  script:
    - scons platform=linux -j$(nproc)

