image: python:3.14

before_script:
  - pip install scons

variables:
  GODOT_CPP_PATH: godot-cpp
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key:
    files:
      - .gitmodules
      - $GODOT_CPP_PATH/.git/HEAD
  paths:
    - $GODOT_CPP_PATH/bin/
    - $GODOT_CPP_PATH/gen/
    - $GODOT_CPP_PATH/src/
    - .sconsign.dblite

build_project:
  stage: build
  script:
    - scons platform=linux -j$(nproc)

